sonar.organization=etch-markup
sonar.projectKey=etch-markup_etch
sonar.projectName=etch
sonar.projectVersion=latest
sonar.links.homepage=https://github.com/etch-markup/etch
sonar.links.scm=https://github.com/etch-markup/etch
